const data = {
    products:[
        {
            _id:'1',
            name:'Green Bomber Jacket',
            category:'Jackets',
            image:'/images/product1.png',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Grey Bomber Jacket',
            category:'Jackets',
            image:'/images/product2.png',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Black Bomber Jacket',
            category:'Jackets',
            image:'/images/product3.png',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Red Bomber Jacket',
            category:'Jackets',
            image:'/images/product4.png',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Funny Shirt',
            category:'Shirts',
            image:'/images/product5.png',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Failure Shirt',
            category:'Shirts',
            image:'/images/product6.png',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};
export default data;